### ISSUE TITLE
Swift 3.0 Issue

### ISSUE THREAD

**Issue by iosappshub** [Skyscanner/SkyFloatingLabelTextField#107]
While installing the framework via Pods, I am getting the swift version error as attached.
Kindly provide help.

I am using XCode 8.0: pod 'SkyFloatingLabelTextField', '~> 2.0.0'
![screen shot 2017-02-12 at 11 51 37 pm](https://cloud.githubusercontent.com/assets/1165864/22864850/d278e0b2-f17e-11e6-8839-4458d020e192.png)

**Comment by k0nserv** [comment]
Is this the only pod you are using? See https://github.com/CocoaPods/CocoaPods/issues/6240 about issues that can arise when different libraries try to use different versions of Swift.

**Comment by iosappshub** [comment]
@k0nserv I figure out that it required to update the cocoapods. I updated cocoapods and everything worked fine. Thanks for your help.

**Comment by k0nserv** [comment]
Glad it worked out! Best of luck with your app :)
