### ISSUE TITLE
How to use in swift3.0

### ISSUE THREAD

**Issue by Seroja1010** [Skyscanner/SkyFloatingLabelTextField#108]
When I am install it using cocoapods, swift version is 2.3.
Can you fix it out?

**Comment by bogren** [comment]
Hey :) I need more info to be able to help. Are you using any other pods? What version of cocoapods are you running? Try running `pod repo update` before install.

**Comment by dexcell** [comment]
I found out that you need to explicitly set SWIFT_VERSION to 3.0 in your project build settings, if you are using objective c project.

or you can add these script on your cocoapod file, then xcode wont ask you to convert the code.
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
	    if target.name == 'SkyFloatingLabelTextField'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end
```

**Comment by k0nserv** [comment]
You can also put the swift version in `.swift-version` in the root of your repo and CocoaPods will pick it up.
