### ISSUE TITLE
Text is not set to right while select arabic language from app

### ISSUE THREAD

**Issue by ibhavin** [Skyscanner/SkyFloatingLabelTextField#109]
I have implemented localization Internally(To change language inside app) in app by using this github repo : [ios_language_manager](https://github.com/maximbilan/ios_language_manager#method-2)

While changing language from app (Not iPhone language) from English to Arabic it is not changing UITextFiled's placeholder text and value to RTL. But if I change the iPhone language to Arabic then it works perfectly.

**_Both of the below textfield's text alignment is natural from storyboard._**
**Without text input only placeholder text** _(Placeholder should come from right side)_
![screen shot 2017-02-21 at 12 36 22 pm](https://cloud.githubusercontent.com/assets/16459948/23154073/f1b1c458-f831-11e6-870d-db50b604b6f7.png)

**With text input and floating placeholder** _(Text should come from right side)_
![screen shot 2017-02-21 at 12 36 49 pm](https://cloud.githubusercontent.com/assets/16459948/23154074/f213e4c6-f831-11e6-81fd-c2958d1dfaca.png)

If I change language from iPhone settings then it works perfectly.

**Without text input only placeholder text** _(Perfect)_
![screen shot 2017-02-21 at 12 46 53 pm](https://cloud.githubusercontent.com/assets/16459948/23154328/47d132a0-f833-11e6-92bd-79c6b2ad12ad.png)

**With text input and floating placeholder** _(Perfect)_
![screen shot 2017-02-21 at 12 47 11 pm](https://cloud.githubusercontent.com/assets/16459948/23154330/485ddeb2-f833-11e6-9be3-d2d94ce5f2b3.png)

**Comment by bogren** [comment]
As far as I understand [ios_language_manager](https://github.com/maximbilan/ios_language_manager#method-2) swaps out the bundle files but doesn't set the properties of the language `LTR = true`. I found this property of `UIView` [semanticcontentattribute](https://developer.apple.com/reference/uikit/uiview/1622461-semanticcontentattribute). Either you make a pull request the ios_language_manager to make sure the lib can handle LRT languages or as you change language in your app you set the `semanticcontentattribute` property. I think this works `UIView.appearance().semanticContentAttribute = .forceRightToLeft` :)

**Comment by ibhavin** [comment]
@bogren  I have put  `UIView.appearance().semanticContentAttribute = .forceRightToLeft` when I change to arabic from english but issue is not solved.

**Comment by bogren** [comment]
Ah okay. I'm looking at some of the previous issues we have reported, I'll try to read up on what is not working with LTR for SkyFloatingLabelTextField. If you find a solution to fix please submit a PR :)

**Comment by k0nserv** [comment]
I think this might relate to the fact that we explicitly set alignment rather than using natural alignment

**Comment by Mehrdadmaskull** [comment]
I'm having the same issue too. With or without setting the alignment.

**Comment by k0nserv** [comment]
Thanks for the PR @Mehrdadmaskull, can you retest against master?

**Comment by k0nserv** [comment]
The PR from @Mehrdadmaskull is merged and was released as part of 3.1.0. Please try this version

**Comment by Maryom** [comment]
Hey,

Thanks for this helpful issue. I have a problem: in Main.strings (Arabic) I wrote:
`"YGo-es-Lf5.placeholder" = "كلمة المرور";`

But as you can see in the image below the field didn't change! how can I change it?

Thanks.

<img width="225" alt="screen shot 2017-05-09 at 11 13 25 am" src="https://cloud.githubusercontent.com/assets/3218401/25841444/d421c9fc-34a8-11e7-8081-40694fd24701.png">

**Comment by k0nserv** [comment]
@bogren care to comment. I don't exactly remember the details of iOS localization anymore. Make sure the id matches the id of the textfield is all I can think of

**Comment by shaileshnparkhi** [comment]
Hi all,
I am having the same issue , when I change Language from arabic to english or vice versa SkyFloatingLabelTextField is not updating according to LTR or RTL.

My xcode version : 10.1
SkyFloatingLabelTextField version : 3.6.0

**Comment by pranavpari** [comment]
> Hi all,
> I am having the same issue , when I change Language from arabic to english or vice versa SkyFloatingLabelTextField is not updating according to LTR or RTL.After restarting the app LTR and RTL is working for SkyFloatingLabelTextField,but when I am changing language, runtime it is not updating.
> 
> My xcode version : 10.1
> SkyFloatingLabelTextField version : 3.6.0

Any solution for this?

**Comment by jawaduzi** [comment]
(SkyFloatingLabelTextField).placeholder =  NSLocalizedString("Write here string for localization", comment: "")
e.g
serachTextField.placeholder =  NSLocalizedString("Search for restaurant", comment: "")

**Comment by shalithacodezync** [comment]
This issue Still Exits On the Latest..As a workaround you will have to handle it by own .. i was able to handle this like this
We only needed support for arabic language.




```

import UIKit

import SkyFloatingLabelTextField

class SkyFloatingUITextFeildWithRtl: SkyFloatingLabelTextField  {
    
    
    override func layoutSubviews() {
        super.layoutSubviews()
        checkForArabicLanguage()
    }
    
    
    private func checkForArabicLanguage(){
        if (ApplicationServiceProvider.shared.isCurrentAppLanguageArabic()){
            isLTRLanguage = false
        }else {
            isLTRLanguage = true
        }
        
    }
    
    
}

```

Then applied this Custom class as View on Storyboard and Outlet..Done

**Comment by kishlaykishore1** [comment]
func textfieldAlingment(_ lang: String){
        if lang == "en" {
            txtNewPassword.textAlignment = .natural
            txtReenterPassword.textAlignment = .natural
        } else {
            txtNewPassword.textAlignment = .right
            txtReenterPassword.textAlignment = .right
        }
    }

**call it in View Will Appear**
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        if UserDefaults.standard.object(forKey: "appLanguage") as? String == "en" {
            UIView.appearance().semanticContentAttribute = .forceLeftToRight
            textfieldAlingment("en")
        }else if UserDefaults.standard.object(forKey: "appLanguage") as? String == "ar"  {
            UIView.appearance().semanticContentAttribute = .forceRightToLeft
            textfieldAlingment("ar")
        }
    }
