### ISSUE TITLE
Unknown class SkyFloatingLabelTextField in Interface Builder file

### ISSUE THREAD

**Issue by dexcell** [Skyscanner/SkyFloatingLabelTextField#111]
Hi, i've got problem using carthage in objective c project.

I can't change UITextField custom class to SkyFloatingLabelTextField using Interface builder.
Somehow IB cannot detect `SkyFloatingLabelTextField`.

If i run the project, the UITextField stays the same, and console will say `Unknown class SkyFloatingLabelTextField in Interface Builder file`

There is no problem creating using code though.

Thanks

**Comment by k0nserv** [comment]
Hi 👋

A few question to pinpoint the issue

+ How did you install `SkyFloatingLabelTextField`? 
+ If you're using CocoaPods did you open `<Project>.xcworkspace`?

**Comment by dexcell** [comment]
Hi,

- Installed it using carthage -> add `github/SkyFloatingLabelTextField` to `Cartfile` and do  `carthage update SkyFloatingLabelTextField`
- If using cocoapod, everything is working properly, Interface builder can detect class SkyFloatingLabelTextField.
- Module and class not detected in interface builder when using carthage framework.

**Comment by k0nserv** [comment]
Hmm. I'm unfortunately not at all familiar with Carthage, but I'll try and have a look at this. @bogren are you more familiar maybe?

**Comment by k0nserv** [comment]
This works for me. See the attached zip.

I had to do a few things to make this work.

1. Add the copy files steps as described [here](https://github.com/Carthage/Carthage/issues/616)
2. Make sure the swift standard library embded as described [here](https://stackoverflow.com/questions/26024100/dyld-library-not-loaded-rpath-libswiftcore-dylib)
3. Use module SkyFloatingLabelTextField and class SkyFloatingLabelTextField in interface builder

[TestIssue111.zip](https://github.com/Skyscanner/SkyFloatingLabelTextField/files/882404/TestIssue111.zip)

**Comment by craigotis** [comment]
I'm seeing the same issue as described by @dexcell

**Comment by k0nserv** [comment]
Does the project from the attached zip work for you?

**Comment by k0nserv** [comment]
@craigotis did you get it working?

**Comment by craigotis** [comment]
Hi @k0nserv, thanks for checking back, but unfortunately I moved to a different framework/implementation for this sort of thing! Hope this is/gets resolved for you guys!

**Comment by k0nserv** [comment]
Okay :) Best of luck 👍

**Comment by CrisBarreiro** [comment]
It might be a bit late to comment on this issue, but using module `SkyFloatingLabelTextField` fixed the issue
