### ISSUE TITLE
UIAppearance Customization

### ISSUE THREAD

**Issue by eggnima** [Skyscanner/SkyFloatingLabelTextField#113]
Would it be possible to allow for the designables to be customized via the UIAppearance proxy?

**Comment by k0nserv** [comment]
That's a good idea for sure! I'll have a look at it at some point, but we're open to anyone contributing it as a PR.

**Comment by k0nserv** [comment]
There's an open pr for this now #118

**Comment by k0nserv** [comment]
Fixed in #118
