### ISSUE TITLE
Need this for TextView

### ISSUE THREAD

**Issue by kmuddapu** [Skyscanner/SkyFloatingLabelTextField#119]
Thanks for a great library.
It Works great for TextField. I need this for TextView.Can anyone please help me !!!

Thank You

**Comment by k0nserv** [comment]
Hey @kmuddapu, 

unfortuantely it's unlikely that we'll ever support `UITextView`.

**Comment by ahmedsafadii** [comment]
+1

**Comment by hardikamal** [comment]
+1

**Comment by HariNarayanan777** [comment]
I am also need this.. +1
...  Please

**Comment by ahmedsafadii** [comment]
+1

**Comment by k0nserv** [comment]
At most we can consider a PR that implements this, but honestly it might be better to make a separate project instead.

**Comment by fadizant** [comment]
+1

**Comment by Isuru-Nanayakkara** [comment]
+1
