### ISSUE TITLE
Setting 'isLTRLanguage'  manually

### ISSUE THREAD

**Issue by maasim94** [Skyscanner/SkyFloatingLabelTextField#120]
I want to set 'isLTRLanguage' for only one text filed but i'm not able to access 'isLTRLanguage'. 
it says 
'isLTRLanguage' is inaccessible due to 'internal' protection level

**Comment by k0nserv** [comment]
Hey @maasim94 you're right that variable has not been opened up. I will do that now :)

**Comment by maasim94** [comment]
will I need to copy resource files to make changes or pod version will updated?

**Comment by k0nserv** [comment]
I'll release a new pod version

**Comment by maasim94** [comment]
Thanks a lot
