### ISSUE TITLE
Can I override titleFormatter?

### ISSUE THREAD

**Issue by ezar** [Skyscanner/SkyFloatingLabelTextField#122]
Hi,
I don't want to use uppercase. Can we change it? How?
Regards,

**Comment by k0nserv** [comment]
Hi @ezar! You sure can just do

```swift
textfield.titleFormatter = { $0 }
```

or if the source title is uppercase

```swift
textfield.titleFormatter = { $0.lowercased() }
```

**Comment by jmamegroot** [comment]
Can you change the font of the titleFormatter?

**Comment by raid5** [comment]
Nice! It would be great if this was mentioned in the docs.
