### ISSUE TITLE
M_PI compiler warning still on 3.0.0

### ISSUE THREAD

**Issue by fishfisher** [Skyscanner/SkyFloatingLabelTextField#123]
FYI: The latest releasse 3.0.0 still warns about M_PI on line 77 SkyFloatingLabelTextFieldWithIcon. Updated with CocoaPods. I tried to download the latest release via zip as well and it still uses M_PI.
No biggie, just thought you should know:)

Keep up the great work!

Erik

**Comment by bogren** [comment]
The M_PI is available on the `master` branch and will be included in the next version 🙂

**Comment by fishfisher** [comment]
Aa, I see! Perfect, thanks😊👍
tor. 6. apr. 2017 kl. 16.30 skrev Emil Bogren <notifications@github.com>:

**Comment by k0nserv** [comment]
I'll release a new version soon. Just waiting for #118 to be merge first.
