### ISSUE TITLE
Add custom icon

### ISSUE THREAD

**Issue by ImranIB** [Skyscanner/SkyFloatingLabelTextField#133]
How to add custom icon in uitext field? Any help. I am currently using font awesome library to add icon but now I want to add icon from assets folder.  

emailTextField.iconFont = UIFont(name: "FontAwesome", size: 15)
emailTextField.iconText = "\u{f0e0}"

**Comment by bogren** [comment]
Hey, did you get it to work? Make sure you successfully import `FontAwesome` in your project.

**Comment by ImranIB** [comment]
Thanks for the response.
