### ISSUE TITLE
title label upper case only first word

### ISSUE THREAD

**Issue by ImranIB** [Skyscanner/SkyFloatingLabelTextField#135]
In text field title it shows capitalized string. Can it be possible to upper case only first word of string like Email?

**Comment by ImranIB** [comment]
Resolved the issue by using textField.titleFormatter = { $0 }

**Comment by phinguyenterralogic** [comment]
For Ojective-C:
textField.titleFormatter = ^(NSString* text){
        return text;
    };

**Comment by RowanG1** [comment]
Where to put code? ViewDidLoad?
