### ISSUE TITLE
Leaving titleLabel as-is during edit

### ISSUE THREAD

**Issue by kalmurzayev** [Skyscanner/SkyFloatingLabelTextField#139]
Hi!
I was wondering, what's the best way to disable turning titleLabel to uppercase when user starts typing?
You have titleFormatter, so I tried inheriting your class and overriding titleFormatter:
```
override  var titleFormatter:(String -> String) = { (text:String) -> String in
        return text;
    }
```

But that gives a `Cannot override with a stored property` error

**Comment by ChrisGriffiths** [comment]
@kalmurzayev you can set the closure to a different value like below, as titleFormatter is stored as a var

```
let textView = SkyFloatingLabelTextField(frame: .zero)
textView.titleFormatter = { (text: String) -> String in
    //Or what ever you want
    return text.lowercased()
}
```

**Comment by kalmurzayev** [comment]
@ChrisGriffiths Oh so you just change the value of titleFormatter property. Thanks, man.
