### ISSUE TITLE
Failed to install it via Carthage after release 3.1.0

### ISSUE THREAD

**Issue by adrianodiasx93** [Skyscanner/SkyFloatingLabelTextField#143]
I can no longer install it via Carthage (version: 0.22.0) after the last release. When I try:
> carthage update --platform iOS SkyFloatingLabelTextField

I get:

>Build Failed. Task failed with exit code 65. This usually indicates that project itself failed to compile.

Deployment Targert: 9.0; Xcode 8.3.2

Version 3.0.0 installation still works fine. Thanks for attention.

**Comment by bogren** [comment]
Hey, are you still experiencing issues installing `SkyFloatingLabelTextField`?

**Comment by k0nserv** [comment]
I'll have a look at this soon, but if you can upload a reproducible case that'd be helpful

**Comment by k0nserv** [comment]
I can't reproduce this albeit in Xcode 8.2.1.

**Comment by k0nserv** [comment]
@adrianodiasx93 Did you make this work?
