### ISSUE TITLE
IconTextField.updateColors() infinite loop

### ISSUE THREAD

**Issue by neoneye** [Skyscanner/SkyFloatingLabelTextField#144]
I just downloaded SkyFloatingLabelTextField. It's pretty nice.

In the Example project I tapped the `Custom layout by subclassing` button and it crashed. I would expect it to push a child view controller, but nothing happened.
![screenshot of simulator](https://i.imgur.com/dMnP6lD.png)

In Xcode it appears to be because of an infinite loop
![screenshot of xcode](http://i.imgur.com/ieoPNtF.jpg)

Xcode 8.3.1 (8E1000a)
macOS Sierra 10.12.4

Steps to reproduce the crash:
 - Select iPhone5s (10.3)
 - Run the project
 - Tap the `Custom layout by subclassing`
 - Boom

**Comment by k0nserv** [comment]
Thanks for raising that doesn't seem corret at all. I wonder how it ever worked 🤔
