### ISSUE TITLE
Clear button is gets overlapped with text?

### ISSUE THREAD

**Issue by kidsid-Ixigo** [Skyscanner/SkyFloatingLabelTextField#147]
When clearButtonMode is set to .whileEditing, The text gets overlapped with text.
In my opinion, the culprit is this overridden method. It doesn't consider the clearButtonMode while returning the CGRect. The width should be less while clearButtonMode is .whileEditing.

```swift
override open func editingRect(forBounds bounds: CGRect) -> CGRect {

        let rect = CGRect(

            x: 0,

            y: titleHeight(),

            width: bounds.size.width,

            height: bounds.size.height - titleHeight() - selectedLineHeight

        )

        return rect

    }
```

**Comment by k0nserv** [comment]
You are very correct :) Thanks for reporting that, I'll get it fixed
