### ISSUE TITLE
Shared is unavailable: use view controller based solutions where appropriate instead. 

### ISSUE THREAD

**Issue by bradlgray01** [Skyscanner/SkyFloatingLabelTextField#150]
![screen shot 2017-06-19 at 4 43 28 pm](https://user-images.githubusercontent.com/25492021/27310355-7d07c172-550e-11e7-8c9e-ff8987b165ce.png)

This error is occurring for me. Any suggestions?

**Comment by bogren** [comment]
Swift version?

**Comment by bradlgray01** [comment]
yes

**Comment by k0nserv** [comment]
Hey :) What's your version of swift, deployment target and xcode version?

**Comment by bradlgray01** [comment]
I'm using swift 3, deployment 10.2.

**Comment by k0nserv** [comment]
and Xcode?

**Comment by bradlgray01** [comment]
xcode 8.3.3. And I think I'm actually using Swift 3.1 as that is what is needed on Xcode 8.3.3

**Comment by k0nserv** [comment]
Does this help https://stackoverflow.com/questions/34225213/uiapplication-sharedapplication-not-available?

**Comment by bradlgray01** [comment]
Unfortunately no. I just check, and my my Only App Extension is set to no.

**Comment by k0nserv** [comment]
and this is a regular iOS app not an extension or module?

**Comment by bradlgray01** [comment]
yep

**Comment by k0nserv** [comment]
@bradlgray01 can you reproduce this with a blank project? I'm on 8.2.1. I'll update and report back. @bogren which version are you on?

**Comment by bradlgray01** [comment]
Hmm... It works on a fresh project. So strange. I guess it's my end that something is gone awry. It's fine I'll, I'll do some more research to see whats going on in my end.

**Comment by k0nserv** [comment]
Okay :) Please let me know if you figure it out :)

**Comment by bradlgray01** [comment]
Will do, and thanks for your help, much appreciated .

**Comment by mmmahajan** [comment]
Hi I solved this problem.

Set to Allow API Extension to No to particular framework who gives this e
error like IQKeyboardManager

Consider you facing this issue for IQKeyboardManager and you installed this framework using Pod. Then your project click on Pod -> CLick on IqkeyboardManager.

And set Allow API Extension to No

**Comment by alvincrisuy** [comment]
@mmmahajan You rock! Your suggestion works like a charm!

**Comment by niclaughter** [comment]
So interestingly, @mmmahajan's solution worked to silence the error in the pod I installed, but in the module I'm trying to access `shared` from the same error is popping up now. I've verified that this setting is set to "NO" in the project file as well.

**Comment by nitrochaien** [comment]
Thank you so much @mmmahajan, u just save my life man

**Comment by sai-manoj-kumar** [comment]
In my case, I had to remove the view controller from sources list of the Extension target instead. The extension is supposed to have this flag to YES. But my file is not intended to be part of this target.

**Comment by firaseljerdy** [comment]
@mmmahajan hey! Where can I find this setting? I am clicking over my framework in the Pod folder in my project.
