### ISSUE TITLE
Field size changes automatically

### ISSUE THREAD

**Issue by timqzm** [Skyscanner/SkyFloatingLabelTextField#152]
I've made some work and commit changes, everything was nice. Now when I open storyboard file, SkyFloatingLabelTextField fields quickly resize.
![screen shot 2017-06-22 at 16 38 13](https://user-images.githubusercontent.com/13407092/27437613-79b8273c-576b-11e7-9f94-85f07d719988.png)
All constraints have right values, but look wrong.
![screen shot 2017-06-22 at 16 41 37](https://user-images.githubusercontent.com/13407092/27437686-b48b0c3a-576b-11e7-9f95-ddaa68603553.png)
Fields look such narrow on device too.
I haven't seen such effect with any other classes :(
Should I provide some code?

**Comment by k0nserv** [comment]
I suspect this is not an issue with SkyFloatingLabelTextField, but your constraints causing this behaviour. There's very little code that deals with the outer bounding box of the field in SkyFloatingLabelTextField

**Comment by MincDev** [comment]
I am now experiencing the exact same. My textboxes worked fine and I didn't change anything except assign their class to SkyFloatingTextField. Now when I close xcode and open it again, all constraints are messed up. I can fix them and they are fine. But when I close xcode again and open up, then they are messed up again.
