### ISSUE TITLE
Use of undeclared identifer

### ISSUE THREAD

**Issue by hemangshah** [Skyscanner/SkyFloatingLabelTextField#155]
# Report

## What did you do?

I just imported the source code files in my project.

## What did you expect to happen?

I should able to use the SkyFloatingLabelTextField.

## What happened instead?

Giving me an error. **Use of undeclared identifier**.

## Environment

Xcode 9.1 and iOS 9.0

Xcode Version:
SkyFloatingLabelTextField Version: latest
Deployment Target: 9.0
Base SDK: 9.0
Method of Integration: Manual

**Comment by k0nserv** [comment]
Hey @hemangshah did you solve this issue?

**Comment by hemangshah** [comment]
@k0nserv, Yes, I have solved this issue. 

https://stackoverflow.com/questions/44904556/use-of-undeclared-identifier-in-xcode-9-0/44905219?noredirect=1#comment76788221_44905219

I was creating a folder name 'SkyFloatingLabelTextField' and then putting all the source inside it. I changed the folder name and it worked for me.

**Comment by k0nserv** [comment]
Glad it worked all though I recommend you use CocoaPods for integration instead of doing it manually
