### ISSUE TITLE
Changing Font in SelectedTitle and Making it not All Caps

### ISSUE THREAD

**Issue by nestorAppsolutely** [Skyscanner/SkyFloatingLabelTextField#169]
Hi, 

I was wondering how to make the floating Label not All Caps. Just as Is. and Also to change its Font to a custom font (PT Sans). I tried to modify the titleFormatter so that it doesn't return a uppercased text, which is the default, but it didn't work.. I also set the titleFont to my preferred font but didn't work as well. Hoping to hear from you. Thanks!

**Comment by k0nserv** [comment]
Both the options you've mentioned should work to solve your problem. Can you share a project that illustrates this?

**Comment by bogren** [comment]
Can you share the code you tried? See #139

**Comment by nestorAppsolutely** [comment]
Hello, I tried your suggestion bogren and it worked. Thanks!
