### ISSUE TITLE
Autolayout issue when using scroll view

### ISSUE THREAD

**Issue by ImranIB** [Skyscanner/SkyFloatingLabelTextField#170]
# Report

## What did you do?

Adding sky floating label text fields using scroll view

## What did you expect to happen?

Email text field not showing at proper place after autolayout using scroll view

## What happened instead?

Email text field which is currently at top can show above password in normal scenario.

## Environment

Please fill in this section with information about your environment

Xcode Version: 8.3
SkyFloatingLabelTextField Version: 'SkyFloatingLabelTextField', '~> 3.0'
Deployment Target: 10.0
Base SDK:
Method of Integration: CocoaPods | Carthage | Manual: Using cocoapods

## Project that demonstrates the issue

![login](https://user-images.githubusercontent.com/10369328/30731252-c1cbceae-9f85-11e7-8ad4-7cf6bdeee99f.png)

**Comment by k0nserv** [comment]
Hey @ImranIB can you reproduce this outside of your own project? It's hard to gague what the issue might be without a runnable project

**Comment by ImranIB** [comment]
Just add multiple text fields in a scroll view and do the Autolayout part. Check if the text fields work properly in the scroll view using autolayout.

**Comment by danya0365** [comment]
Me too.

**Comment by bogren** [comment]
How are you laying out the views? As @k0nserv said, are you able to reproduce this outside of your project? Are both fields affected when scrolling? I suspect there is an issue in how you setup the constraints.
