### ISSUE TITLE
 Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [Skyscanner/SkyFloatingLabelTextField#172]
Just updated my Xcode and using swift 4. 
Xcode = Version 9.0 (9A235)
iOS version 10.0
pod --version 1.3.1

When I try to change target swift version to 3.2 I get this error 
<img width="598" alt="screen shot 2017-10-02 at 1 42 47 pm" src="https://user-images.githubusercontent.com/18103561/31074144-e872dc92-a777-11e7-91b7-7d9008a12774.png">
<img width="746" alt="screen shot 2017-10-02 at 1 43 07 pm" src="https://user-images.githubusercontent.com/18103561/31074145-e8879fa6-a777-11e7-93c4-4711e2017bdb.png">

Then changing it to swift 4 I get 6 errors mentioned in See [#158](https://github.com/Skyscanner/SkyFloatingLabelTextField/issues/158)

<img width="205" alt="screen shot 2017-10-02 at 1 46 33 pm" src="https://user-images.githubusercontent.com/18103561/31074197-211d0f7c-a778-11e7-8314-7c02450b050b.png">

**Comment by k0nserv** [comment]
What integration method are you using?

**Comment by AbdulazizAlmohsen** [comment]
Pod

**Comment by k0nserv** [comment]
Did you use the post_install hook from https://github.com/Skyscanner/SkyFloatingLabelTextField/issues/158 to change the version?

**Comment by AbdulazizAlmohsen** [comment]
No I actually haven't figured out how to use. Can you please guide me

**Comment by k0nserv** [comment]
Sure, see this comment on the thread linked in #158 https://github.com/CocoaPods/CocoaPods/issues/6791#issuecomment-320028044

**Comment by AbdulazizAlmohsen** [comment]
Just this in my pod file ?
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'SkyFloatingLabelTextField'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
```

**Comment by k0nserv** [comment]
Yeah

**Comment by AbdulazizAlmohsen** [comment]
This is what my pod looks like. Is that correct ?

```
pod 'OneSignal', '>= 2.5.2', '< 3.0'
pod 'RQShineLabel'
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'SkyFloatingLabelTextField'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!

  pod 'OneSignal', '>= 2.5.2', '< 3.0'
end
```

**Comment by k0nserv** [comment]
Yeah

**Comment by AbdulazizAlmohsen** [comment]
I'm sorry but it's not installed with the other pods. Can you please check the pod structure for me. First time to use the hook :)

**Comment by k0nserv** [comment]
I've just pushed a Swift 3/4 compatible fix in a5fe9c9 can you try point directly to git for `SkyFloatingLabelTextField` per the comment in #158 ?

**Comment by AbdulazizAlmohsen** [comment]
thank you

**Comment by k0nserv** [comment]
I take it that worked?

**Comment by AbdulazizAlmohsen** [comment]
Yeah

**Comment by k0nserv** [comment]
Great stuff, I'll look at releasing this in the coming week. In the meantime you can keep running against master
