### ISSUE TITLE
Objective-C issues

### ISSUE THREAD

**Issue by ml012** [Skyscanner/SkyFloatingLabelTextField#174]
When I use SkyFloatingLabelTextField in storyboard(interface builder) in objective-c project, I had key-value compliant error. 

what is best practice to use in Storyboard in objective-c?

**Comment by bogren** [comment]
That should not be a problem. We're using `SkyFloatingLabelTextField` in storyboard in Objc. How do you install `SkyFloatingLabelTextField`, CocoaPods, Carthage?

**Comment by ml012** [comment]
Yes, sorry, it was my mistakes due to other problem.
