### ISSUE TITLE
Adjusting FLoating Title Distance from bottom

### ISSUE THREAD

**Issue by nestorAppsolutely** [Skyscanner/SkyFloatingLabelTextField#176]
Hello again. How do i Adjust how high the title label floats with respect to the input line? Thanks!

**Comment by pbhatt-mphrx** [comment]
Hi, Any update. I am having same requirement.

**Comment by k0nserv** [comment]
Try setting a higher line height on the font you are using

**Comment by deeplightco** [comment]
If you set a height constraint (larger than default) for the text field it will lay out the line, field and title label with more spacing.
