### ISSUE TITLE
Memory Leak issue

### ISSUE THREAD

**Issue by robertodias180** [Skyscanner/SkyFloatingLabelTextField#179]
# Report

## What did you do?

There is some issue on iOS 11.1, not sure about 11.0 because I did not test it, as for iOS 10 it works like perfectly.

The issue is that once you interact with the view it won ever be dealloc. I added a deinit method to `SkyFloatingLabelTextField.swift` in order to test it, on ios 10 it gets called every time but on 11.1 it does not.

if need I can provide a sample project. 

Xcode Version: 9.1 (9B55)
SkyFloatingLabelTextField Version: 3.3.0
Deployment Target: 9.0
Method of Integration: CocoaPods

**Comment by k0nserv** [comment]
Hmm that's super strange. Thanks for investigating. A sample project would be great

**Comment by k0nserv** [comment]
Just tested this on master with the example project. I'm seeing deinit being called on iOS 11.1 for all cases

**Comment by robertodias180** [comment]
@k0nserv [here](https://github.com/robertodias180/SkyFloatingLabelTextFieldLeekTest) is an example

**Comment by k0nserv** [comment]
That's super strange. I'm not seeign it with that example either. Both the second view controller and the two fields are getting `deinit`ed for me. I'm on Xcode 9.1(9B55) with the iOS 11.1 iPhone 8 Plus simulator. @bogren can you be a third person here?

**Comment by robertodias180** [comment]
@k0nserv if I open and close the view it calls `deinited ` but if you select any of the fields or write any text on them and then click back it does not.

**Comment by k0nserv** [comment]
You are right. It seems like UIkeyboardImpl is keeping a reference to the instances after the view is removed. 

![image](https://user-images.githubusercontent.com/1333960/32551111-58b5abca-c487-11e7-8c8a-cf3bf3379383.png)

**Comment by k0nserv** [comment]
I can replicate this with a regular UITextField. I think this is a iOS bug rather than a SkyFloatingLabelTextField specific issue.

![image](https://user-images.githubusercontent.com/1333960/32551294-eeeca59e-c487-11e7-877d-312b22dabac2.png)

**Comment by robertodias180** [comment]
that makes things worst since we can't fix it...

thanks for the help @k0nserv 😃
