### ISSUE TITLE
Autoresizing textfield text

### ISSUE THREAD

**Issue by AndreaMiotto** [Skyscanner/SkyFloatingLabelTextField#181]
Hi, I'm trying to autoshrink, autoresize the text in the textfield when the text is more length than the textfield width. But when I type in the textfield the text will move out on the left side, and the first letters disappears...

![schermata 2017-11-10 alle 18 07 52](https://user-images.githubusercontent.com/11211914/32669800-18dc424a-c642-11e7-9abf-0c9e2efb6a14.png)

**Comment by k0nserv** [comment]
Can you share the method you are using? This should work the same as for `UITextField` since `SkyFloatingLabelTextField` just inherits from it

**Comment by SzadyDesigns** [comment]
I'm having the same issue.  I'm pre-filling the text for a textField with fetched data from an API call, and the text isn't shrinking to fit.  I've added `textFieldName.adjustsFontSizeToFitWidth = true` as well checking the box in IB and nothing seems to fix it.  Help?

**Comment by Tovkal** [comment]
Apparently UITextField will only go down to a minimum font size of 14. If you set the minimum to 10, it will only reach 14. 

Source: https://stackoverflow.com/a/30881385/1283228
