### ISSUE TITLE
Is it possible to add Custom Image in the place of Icon ??

### ISSUE THREAD

**Issue by joyalserrao** [Skyscanner/SkyFloatingLabelTextField#182]
How to add custom image instated of icon.  I am using swift 4. unable to find icontype enum property . Please help

**Comment by k0nserv** [comment]
Hey, there's https://github.com/Skyscanner/SkyFloatingLabelTextField/pull/159 which is currently not merged. Waiting for @PedroAnibarro1 to get back to me, however I might just merge it if don't here from them

**Comment by joyalserrao** [comment]
Hello @k0nserv  I have done with icon color with image. is it right way ??? but it work well


        let img: UIImage = UIImage(named: "user_id")!
        let imgSize: CGSize = self.password.iconLabel.frame.size
        
       // UIGraphicsBeginImageContext(imgSize)
        UIGraphicsBeginImageContextWithOptions(imgSize, false, 0.0)
        img.draw(in: CGRect.init(x: 0, y: 0, width: imgSize.width, height: imgSize.height ))
        
        let newImage: UIImage = UIGraphicsGetImageFromCurrentImageContext()!
//UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext();
        
        self.password.iconLabel.backgroundColor = UIColor(patternImage: newImage)

**Comment by k0nserv** [comment]
It is now, just released version 3.4.0 with support for this. Thanks to @PedroAnibarro1
