### ISSUE TITLE
Version 3.4.0 change log is missing

### ISSUE THREAD

**Issue by ergunkocak** [Skyscanner/SkyFloatingLabelTextField#185]
Version 3.4.0 change log is missing

[https://github.com/Skyscanner/SkyFloatingLabelTextField/releases](url)

**Comment by k0nserv** [comment]
I screwed up the release it seems. Notes are still in `CHANGELOG.md` though https://github.com/Skyscanner/SkyFloatingLabelTextField/blob/master/CHANGELOG.md#v340
