### ISSUE TITLE
Carthage - Task failed with exit code 65

### ISSUE THREAD

**Issue by D-Mx** [Skyscanner/SkyFloatingLabelTextField#207]
> Before you start, are you using the latest SkyFloatingLabelTextField release?
Yes

# Report

## What did you do?

ℹ Tried to install via carthage, got this meesage 

```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/.../Documents/project/Carthage/Checkouts/SkyFloatingLabelTextField/SkyFloatingLabelTextField.xcworkspace -scheme SkyFloatingLabelTextField -configuration Release -derivedDataPath /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/SkyFloatingLabelTextField/v3.4.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/j_/21wldccs2zvfzks4_lrzwx580000gn/T/SkyFloatingLabelTextField SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/.../Documents/project/Carthage/Checkouts/SkyFloatingLabelTextField)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/j_/21wldccs2zvfzks4_lrzwx580000gn/T/carthage-xcodebuild.4zy5hK.log
```

## What did you expect to happen?

ℹ Framework successfully built

## What happened instead?

ℹ Task failed with exit code 65

## Environment

ℹ     

Xcode Version:  9.3.1 (9E501)
SkyFloatingLabelTextField Version: 3.4.1
Deployment Target: 10.0
Base SDK:
Method of Integration:  Carthage

## Project that demonstrates the issue

ℹ n/a

**Comment by D-Mx** [comment]
I ran carthage again to post the log but with version "v3.5.1" worked, I don't know if that changed anything but it has finally built. Sorry for the inconvenience.

**Comment by k0nserv** [comment]
That's very strange. Nothing about the project itself changed between 3.4.1 and 3.5.1 🤷‍♂️ Glad it worked out though
