### ISSUE TITLE
IBDesignable Issue at stoyboard (Prevents to do anything at storyboard)

### ISSUE THREAD

**Issue by luizcelarino** [Skyscanner/SkyFloatingLabelTextField#212]
# Report

## What did you do?

I'm trying to edit anything within a storyboard that contains a SkyFloatinglabelTextField.
Xcode shows 
![screen shot 2018-06-08 at 12 28 36](https://user-images.githubusercontent.com/29202256/41166823-97a0dc4c-6b17-11e8-894d-155ca88f1ae4.png)
Simulation.storyboard: error: IB Designables: Failed to render and update auto layout status for AddPaymentMethodViewController (XWG-HE-Wbe): dlopen(SkyFloatingLabelTextField.framework, 1): no suitable image found. Did find: SkyFloatingLabelTextField.framework: required code signature missing for 'SkyFloatingLabelTextField.framework'

## What did you expect to happen?

Xcode regular behaviour (ability do edit storyboard)

## What happened instead?

All views that contains a skyfloatinglabeltextfield has an empty view (see attachment)

## Environment

Xcode Version: 9.4
SkyFloatingLabelTextField Version: 3.5.1
Deployment Target: 11
Base SDK: 11.4
Method of Integration: CocoaPods

**Comment by kyaracat** [comment]
Same here. It happened when I updated Cocoapod to the latest version(1.5.3). I downgraded to 1.4.0 and it looks fine for now. I need to update my Cocoapod soon or later tho.

**Comment by tarikstafford** [comment]
same problem here, is there a solution to this?

**Comment by k0nserv** [comment]
Yeah this is covered in https://github.com/CocoaPods/CocoaPods/issues/7606 and https://github.com/Skyscanner/SkyFloatingLabelTextField/issues/201
