### ISSUE TITLE
Main.storyboard: error: IB Designables: Failed to render and update auto layout status for ViewController (BYZ-38-t0r): dlopen(SkyFloatingLabelTextField.framework, 1): no suitable image found.  Did find: 	SkyFloatingLabelTextField.framework: required code signature missing for 'SkyFloatingLabelTextField.framework'

### ISSUE THREAD

**Issue by ajoykarmakar459** [Skyscanner/SkyFloatingLabelTextField#213]
# Report

Firstly I want to give you appreciate for this awesome package but I got some issue while using this.I have Install this package through cocoapods and it's working fine on simulator but the problem begins with xcode preview builder.After adding any input to SkyFloatingLabelTextField, the preview builder is working off and give an error.
<img width="272" alt="screen shot 2018-06-12 at 3 42 12 pm" src="https://user-images.githubusercontent.com/23628008/41284696-a2e271ae-6e57-11e8-9ab9-313e5366e704.png">
Xcode Version is 9.2 (9C40b)

**Comment by k0nserv** [comment]
Hey @ajoykarmakar459 please see #201
