### ISSUE TITLE
Can we make SkyFloatingLabelTextField in multiple line?

### ISSUE THREAD

**Issue by tester87** [Skyscanner/SkyFloatingLabelTextField#214]
Hi all,

Is it possible to make it 2 or more lines for SkyFloatingLabelTextField? Understand it can be done in UITextView. Please help, thanks!

**Comment by k0nserv** [comment]
Hey @tester87, unfortunately this is not possible because the underlying UI component would have to be configurable. `UITextField` which `SkyFloatingLabelTextField` is based on can only handle a single line

**Comment by tester87** [comment]
Hi k0nserv, noted with thanks!
