### ISSUE TITLE
Crash on titleFormatter property

### ISSUE THREAD

**Issue by Dalein** [Skyscanner/SkyFloatingLabelTextField#230]
# Report

## What did you do?
Set block to  txtField.titleFormatter

## What did you expect to happen?
configuration of placeholder text format

## What happened instead?
Crash on line  `txtField.titleFormatter = { (text: String) in return text }`
**Thread 1: EXC_BAD_ACCESS (code=257, address=0x1a1b723bec9)**

## Environment

Xcode Version: 9.4.1 (9F2000)
SkyFloatingLabelTextField Version: 3.5.1
Deployment Target: iOS 11.4
Base SDK: iOS 10.0
Method of Integration: CocoaPods

**Comment by k0nserv** [comment]
Is this reproducible in a barebones project? Can you attach an example project if so?

**Comment by Dalein** [comment]
Sorry, it was my mistake. I incorrectly connected IBOutlets.
