### ISSUE TITLE
XCode 10 Swift 4.2 can't archive

### ISSUE THREAD

**Issue by LastSprint** [Skyscanner/SkyFloatingLabelTextField#241]
# Report

## What did you do?

I archived my project (release config)

## What did you expect to happen?

I excepted successful build

## What happened instead?

I have the error: `abort trap:6` and in the bottom of  error log
```
2.	While running pass #1768320 SILFunctionTransform "SpeculativeDevirtualization" on SILFunction "@$S25SkyFloatingLabelTextFieldAAC4TwimE18configureForSignIn33_604294689B813157BF26F70B546FAE81LL4withySS_tF".
 for 'myFuncThatConfigSFLT(with:)' at /Users/aleksandrkravcenkov/twim-ios/Twim/User Stories/Login/EnterApiKey/View/EnterApiKeyViewController.swift:194:5
3.	While deserializing SIL vtable for 'SkyFloatingLabelTextField' in module 'SkyFloatingLabelTextField'
```

In debug builds successfully
## Environment

Xcode Version: 10.0 (10A255)
SkyFloatingLabelTextField Version: v3.6.0
Deployment Target: iOS 10.3
Base SDK: iOS 12
Method of Integration: CocoaPods 

## Project that demonstrates the issue

n/a

**Comment by sandeepbol** [comment]
I also have the same issue but with another third party library called 'UICircularProgressRing'. I think the problem is not related to the particular library but may be a bug with Xcode 10.

**Comment by LastSprint** [comment]
Yes. I reincluded all my source code files and this error dissappeared

**Comment by sandeepbol** [comment]
Where is Valid architectures setting in Xcode 10? I couldn't find it.
<img width="640" alt="screen shot 2018-10-09 at 9 44 30 am" src="https://user-images.githubusercontent.com/25767241/46646475-0003e680-cba8-11e8-93f2-c8289b2a42db.png">

**Comment by sandeepbol** [comment]
It might help others. I did following things - don't know what helped but I was able to archive my app

1) Remove armv7 from valid architectures of a private dynamic framework that I was using.
2) Deintegrate/Integrate Pods again.

I still don't have an option of setting valid architectures for my Xcode project.

**Comment by ahmed-sal** [comment]
@sandeepbol , you need to select the `All` tab in the build settings (right next to the `Basics` tab that is selected in the screenshot)
