### ISSUE TITLE
SkyFloating title level

### ISSUE THREAD

**Issue by sunkumar** [Skyscanner/SkyFloatingLabelTextField#242]
Dear Team,

I have implemented this class in my couple of projects.

Will it be possible to keep an option as Bool for autocapitalization of title?

Right now all the title going to Caps. My requirement is to keep title as it is placeholder. Although I have edit the pod file but is not the good practice.

Thanks

**Comment by k0nserv** [comment]
Hey @sunkumar you can change this behaviour by setting the `titleFormatter` property

**Comment by NupendraVerma** [comment]
> Hey @sunkumar you can change this behaviour by setting the `titleFormatter` property

Thank You sir
