### ISSUE TITLE
Multi line error 

### ISSUE THREAD

**Issue by JigarPatel1234** [Skyscanner/SkyFloatingLabelTextField#243]
Is there any way to set multiline error in label,
As this is the best floating label textfield till now, we just need one thing and that is multi line error support. if there is some way, please share it to us.
Thank you

Xcode Version: 10
SkyFloatingLabelTextField Version:3.0
Deployment Target:10
Method of Integration: CocoaPods

**Comment by KompoD** [comment]
@k0nserv, it's interesting question. Please answer as soon as u can :)

**Comment by k0nserv** [comment]
Hey, no there's isn't support for that at the moment. I am not sure if it's a good idea to support that as it will cause they UI to "jump around" if the label itself is a single line. I think it would be better to add a shorter error and include something more complete elsewhere in your UI

**Comment by RowanG1** [comment]
> Hey, no there's isn't support for that at the moment. I am not sure if it's a good idea to support that as it will cause they UI to "jump around" if the label itself is a single line. I think it would be better to add a shorter error and include something more complete elsewhere in your UI

I think jumping around will work better. The problem is that you need to have error like : "Invalid Username. At least one character or digit". The "invalid username" for example needs to be included in error so the user can see which field it is.

**Comment by Drusy** [comment]
I can understand Skyscanner team don't want to implement this feature request, if your error message doesn't fit only on small screens such as iPhone SE, you still can consider using `adjustsFontSizeToFitWidth` on the component label:

```swift
titleLabel.adjustsFontSizeToFitWidth = true
titleLabel.minimumScaleFactor = 0.8
```

**Comment by sivakumarec99** [comment]
Hi sir  used your sours file. Good Design sir thank you so much. Good  improve in lable  animation.
