### ISSUE TITLE
Error state flashes if empty text is invalid

### ISSUE THREAD

**Issue by dcaunt** [Skyscanner/SkyFloatingLabelTextField#27]
I have a simple validator which checks if a field is empty (`!text.isEmpty`) and validation occurs when the `shouldChangeCharactersInRange` delegate method is called, as in the README example. I set the floatingLabel's errorMessage if validation fails.

Unfortunately this causes the red error state to flash briefly when text is entered for the first time, as the `shouldChangeCharactersInRange` delegate method is called twice – once by UIKit and once by `SkyFloatingLabelTextField`'s [`editingChanged`](https://github.com/Skyscanner/SkyFloatingLabelTextField/blob/e7e877a1aade779531bdaebbb166076638953209/Sources/SkyFloatingLabelTextField.swift#L309) method.

Any ideas how I can avoid this flash?

**Comment by gergelyorosz** [comment]
This is definitely unwanted behaviour. Let me look into if / how this can be prevented (or fixed).

**Comment by dcaunt** [comment]
Thanks for the quick response. I've looked into this briefly and I'm not sure that manually calling the UITextField delegate methods is a good idea in general, because you can't be sure what side effects will occur as a result. 

In my brief testing, adding a target to each field, listening for `.EditingChanged` events and performing validation there seems to avoid the flashing issue, but I wonder if you're aware of problems this approach might have.

**Comment by gergelyorosz** [comment]
Yes, you're right that it's not good practice to manually invoke the `UITextField` delegates. We originally did this to support a bit convoluted use case around resetting the `errorMessage`.

In [this PR](https://github.com/Skyscanner/SkyFloatingLabelTextField/pull/28) I've addressed this issue - which should fix the blinking. Once reviewed, tested and merged, I'll create a new version for the control.

Thanks again for taking the time to raise this issue!

**Comment by dcaunt** [comment]
I've tested this against my use case, and it appears to be working nicely, so I'll close this issue. Thanks again!

**Comment by justinswart** [comment]
Something about the change in 1.2.0 vs 1.1.1 is causing the placeholder text to appear and immediately disappear on becomeFirstResponse(). I've rolled back to 1.1.1 for now, seems to fix it.  No other code changes on my side, will investigate further soon as I have a chance.
