### ISSUE TITLE
Swift Version issue with CocoaPods

### ISSUE THREAD

**Issue by Eccelor** [Skyscanner/SkyFloatingLabelTextField#275]
# Report

## What did you do?

Tried installing SkyFloatingLabelTextField via CocoaPods

## What did you expect to happen?

Pod should be installed.

## What happened instead?

CocoaPods generated following error
[!] Unable to determine Swift version for the following pods:

- `SkyFloatingLabelTextField` does not specify a Swift version and none of the targets integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

## Environment
Xcode Version: Version 10.1 (10B61)
SkyFloatingLabelTextField Version: 3.6.0
Deployment Target: 10.0
Base SDK: 
Method of Integration: CocoaPods

**Comment by MrVlad001** [comment]
I found solution. Try to use 1.5.3 version of CocoaPods to install pod.

**Comment by Eccelor** [comment]
@MrVlad001 We're currently using 1.6.1

**Comment by MrVlad001** [comment]
@Eccelor OK. Another solution.
Try to create an empty swift file in the project.

**Comment by Eccelor** [comment]
@MrVlad001 That will be a work around. You cannot expect these many users to do that. Its just a simple fix on their part, mention the swift version they're using.

**Comment by k0nserv** [comment]
I've just released version 3.7.0 which if you use it with CocoaPods 1.7.0.rc1 should work well regardless of the verison of Swift you are using in your project.
