### ISSUE TITLE
LLDB error: Couldn't IRGen expression, no additional error

### ISSUE THREAD

**Issue by 93cantero** [Skyscanner/SkyFloatingLabelTextField#277]
# Report
LLDB error: Couldn't IRGen expression, no additional error

Summary:
When using Carthage as a dependency manager to link SkyFloatingLabelTextField in the project causes LLDB to be unable to perform any printing operations. It just prints "error: Couldn't IRGen expression, no additional error" making ultra hard to find the root cause of the issue.

## What did you do?

1) Build the framework in a certain machine using Carthage.
2) Link the framework in an app project.
3) Try to run the application from a different machine.

## What did you expect to happen?

LLDB Debugger to work as usual.

## What happened instead?

error: `Couldn't IRGen expression, no additional error`

## Environment

Xcode Version: 10.1 (10B61)
SkyFloatingLabelTextField Version: 3.6.0
Deployment Target: 10.0
Base SDK: iOS
Method of Integration: Carthage

## Project that demonstrates the issue

Steps to Reproduce:
1) Open the project
2) Set a breakpoint in the ViewController´s viewDidLoad method
3) Run the app
4) "po self"
5) check the LLDB output

[CarthageTest.zip](https://github.com/Skyscanner/SkyFloatingLabelTextField/files/3012632/CarthageTest.zip)

**Comment by k0nserv** [comment]
Check this SO answer and see if that helps

**Comment by k0nserv** [comment]
Closing due to inactive. I assume this has been resolved
