### ISSUE TITLE
Upgrade to swift 5

### ISSUE THREAD

**Issue by jessemx109** [Skyscanner/SkyFloatingLabelTextField#288]
Can you please migrate the project to swift 5

**Comment by andrei-gemini** [comment]
Also there is an issue with SPM:
"The package dependency graph can not be resolved; unable find any available tag for the following requirements:
https://github.com/Skyscanner/SkyFloatingLabelTextField — 3.7.0..<4.0.0"

**Comment by k0nserv** [comment]
This will be released in version 3.8.0

**Comment by k0nserv** [comment]
Released in 3.8.0
