### ISSUE TITLE
Decrease spacing between placeholder and text

### ISSUE THREAD

**Issue by jasnicaa** [Skyscanner/SkyFloatingLabelTextField#291]
Hey thanks for a great library!

I am wondering how to decrease the spacing between placeholder and text?

**Comment by fl034** [comment]
I had the same question and found a solution by subclassing:

```
class MySkyFloatingTextField: SkyFloatingLabelTextField {
    override func titleHeight() -> CGFloat {
        return super.titleHeight() - 4
    }
}
```

But the problem with this is that the text gets clipped a little

**Comment by jasnicaa** [comment]
yes my thoughts exactly but that clipping is a big problem, so I just left it that way although our designer is not happy :D

**Comment by k0nserv** [comment]
As @jasnicaa said subclassing is the suggested approach here, it's not likely that we'll accept any changes to support this
