### ISSUE TITLE
Customize Font for Text

### ISSUE THREAD

**Issue by ahmad-atef** [Skyscanner/SkyFloatingLabelTextField#30]
I couldn't see a method to change the system font for the text. I can see for the place holder and for Selected Label.

Thanks,

**Comment by intonarumori** [comment]
@ahmad-atef Since it is a subclass of `UITextField` you can use the regular `font` property to set the input text font.

**Comment by gergelyorosz** [comment]
@ahmad-atef +1 for the suggestion by @intonarumori . If you execute the following code, the font should be changed:

```
myTextField.font = UIFont(name: "Verdana", size: 20)
```
I just tested this code, and the main text is changed. Please let us know if this works for what you'd like to achieve.

**Comment by gergelyorosz** [comment]
Closing this issue - please let us know @ahmad-atef if you couldn't set the font size using the provided workaround.
