### ISSUE TITLE
Update the Swift PackageManager Support

### ISSUE THREAD

**Issue by jonnyarc** [Skyscanner/SkyFloatingLabelTextField#300]
# Report

## What did you do?

ℹ Add the project as swift package using Xcode 11

## What did you expect to happen?

ℹ Add the package dependency

## What happened instead?

ℹ Error:
The package dependency graph can not be resolved; unable find any available tag for the following requirements:

https://github.com/Skyscanner/SkyFloatingLabelTextField.git — 3.7.0..<4.0.0

## Environment

ℹ

Xcode Version: 11.0 (11A420a)
SkyFloatingLabelTextField Version: Latest
Deployment Target: iOS 12
Base SDK: iOS 13
Method of Integration: SPM

## Project that demonstrates the issue
Simply create a new app and add SPM dependency for this framework

**Comment by k0nserv** [comment]
This should be getting fixed in version 3.8.0

**Comment by k0nserv** [comment]
Fixed in 3.8.0
