### ISSUE TITLE
Add target to the SkyFloatingLabelTextField not working

### ISSUE THREAD

**Issue by Hamza-Almass** [Skyscanner/SkyFloatingLabelTextField#304]
Hi , 

i have an issue about when, i add target value changed to the SkyFloatingLabelTextField it's not working? how can i add it.

thank you

**Comment by Fugos** [comment]
From the README:
"To get notified of different events happening on the textfield - such as the text changing, editing starting or ending - just set the func addTarget(_ target: Any?, action: Selector, for controlEvents: UIControl.Event) with the .editingChanged. also can set the delegate property to a class implementing the standard UITextFieldDelegate protocol"
