### ISSUE TITLE
UITextView suppoort

### ISSUE THREAD

**Issue by zdenektopic** [Skyscanner/SkyFloatingLabelTextField#31]
Is support for UITextView planned or coming?

Z.

**Comment by gergelyorosz** [comment]
Hi @zdenektopic! We created this control to make text input easier - essentially an extension to `UITextField`. `UITextView` is for text displaying: I don't see the use case for creating something similar there.

A lot of the functionality added on top of `UITextView` applies when having a keyboard. E.g. the placeholder disappearing, and the title changing when typing text, or the style being different when the textbox has focus, vs when it does not. With `UITextView` these use cases don't exist quite like this.

What problem are you looking to solve with a customized `UITextView`? What functionality would you expect from such a component?

**Comment by intonarumori** [comment]
@gergelyorosz  `UITextView` is for displaying and editing multiline text.
It would probably be a little bit more complex because of scrolling text, but essentially all of our implementation could be applied to `UITextField`.

**Comment by gergelyorosz** [comment]
Thanks @intonarumori, my bad on missing the editing part. So the use case would be for multiline text then, which is fair.

I think it's a reasonable request - the unfortunate part is that most of the code would have to be re-implemented and tested, both for the version without, and the one without icons. I can't see us adding this in the immediate future, but keeping this request open, so we get around to this.

**Comment by gergelyorosz** [comment]
I'll close this issue as there is not an immediate plan to add UITextView support. I do agree it would make sense though, however I see this being very much down the line - not the least because at Skyscanner we're only using the UITextField version of this control.

**Comment by ThoseGuysInTown** [comment]
Any plans for this yet?

**Comment by k0nserv** [comment]
To my knowledge we are no logner actively using SkyFloatingLabelTextField internally and I as the primary maintainer don't work on iOS in my primary role. I'm open to this being contributed from the community, but it's unlikely we'll implement it ourselves.

**Comment by saranya-chandran** [comment]
Any update on this?
