### ISSUE TITLE
No support for SwiftUI

### ISSUE THREAD

**Issue by maxakash** [Skyscanner/SkyFloatingLabelTextField#313]
I am using SkyFloatingLabelTextField in SwiftUI  . My code is 
```
struct Textfield: UIViewRepresentable {
    func makeUIView(context: Context) -> UITextField {
         let textField = SkyFloatingLabelTextField(frame: CGRect(x: 10, y: 10, width: 200, height: 45))
                             textField.placeholder = "Username"
                             textField.title = "Your full name"
        
        return textField
    }
    

    func updateUIView(_ uiView: UITextField, context: Context) {

    }
}
```

But there is a very large space between the textfield and title.
![Screenshot 2020-03-22 at 2 26 24 PM](https://user-images.githubusercontent.com/17406944/77246014-37a20980-6c49-11ea-9843-b9e6970e4512.png)

Please suggest any solution @unlobito @richardkeen @ivanz

**Comment by k0nserv** [comment]
I think this will be due to the layout used, SwiftUI views by default use the whole proposed size to render. I'm still learning SwiftUI myself so I can't really help here. If you find a solution that requires changes to the library we'd be happy to accept a PR

**Comment by k0nserv** [comment]
So what you probably can do is `Textfield.frame(width: nil, height: 45)`
