### ISSUE TITLE
SkyFloatingLabelTextField doesn't seem to support Dynamic Type

### ISSUE THREAD

**Issue by tciuro** [Skyscanner/SkyFloatingLabelTextField#315]
I have the following code:

        usernameTextField.placeholder = "Username"
        usernameTextField.placeholderFont = UIFont.preferredFont(forTextStyle: .headline)
        usernameTextField.adjustsFontForContentSizeCategory = true
        usernameTextField.title = "Username"
        usernameTextField.titleFont = UIFont.preferredFont(forTextStyle: .headline)
        usernameTextField.adjustsFontForContentSizeCategory = true

I was hoping that either `placeholder` or `title` would pick the `adjustsFontForContentSizeCategory` setting from `usernameTextField`, but they don't.

It would be great if the text fields (or some API) for `placeholder` and `title` were exposed so that we could activate dynamic type.

**Comment by tciuro** [comment]
I have cloned the project and realized that I can also set the font on `placeholderFont`:

        usernameTextField.placeholderFont = UIFont.systemFont(ofSize: 20.0)
        usernameTextField.titleFont = UIFont.systemFont(ofSize: 20.0)

What I see is that originally, the text field honors the size. After typing, the title (above the textfield) still continues to honor the font size, but the actual value of the text field is smaller. I cannot find the place in the code where the font size is being overriden.

How/where is the font size of the field changed with a smaller font?

![after](https://user-images.githubusercontent.com/412899/78598107-87fd9780-7803-11ea-9c53-e719ea41dfc0.PNG)
![before](https://user-images.githubusercontent.com/412899/78598114-8d5ae200-7803-11ea-8b3c-cb62d2d46323.PNG)

**Comment by mluisbrown** [comment]
You also need to do

```swift
usernameTextField.titleLabel.adjustsFontForContentSizeCategory = true
```

**Comment by k0nserv** [comment]
This is intentional for now and there are no plans to add it

**Comment by mluisbrown** [comment]
@k0nserv can you at least explain *why* it's intentional?
