### ISSUE TITLE
New release anytime soon?

### ISSUE THREAD

**Issue by joeboyscout04** [Skyscanner/SkyFloatingLabelTextField#322]
# Report
Any chance we can get a new tagged release to include the latest goodies, including the addition of the `errorPlacement` option?  

https://github.com/Skyscanner/SkyFloatingLabelTextField/compare/3.8.0...master

We can use the current master branch for the moment but would be cleaner to have a tagged release we can point to.  Thanks!

**Comment by k0nserv** [comment]
4.0.0 was just released
