### ISSUE TITLE
Xcode 12 SPM `IPHONEOS_DEPLOYMENT_TARGET` warning

### ISSUE THREAD

**Issue by diogot** [Skyscanner/SkyFloatingLabelTextField#324]
# Report

## What did you do?

Using SkyFloatingLabelTextField in SPM on Xcode 12 GM.

## What did you expect to happen?

Don't show any build warning.

## What happened instead?

Produces this warning:

> The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

## Environment

Xcode Version: 12 GM
SkyFloatingLabelTextField Version: 3.8.0
Deployment Target: iOS 12
Base SDK: iOS 14
Method of Integration: SPM

According to [this thread](https://forums.swift.org/t/minimum-ios-version-xcode-12-and-build-warnings/40224/3) the problem is that  [this](https://github.com/microsoft/plcrashreporter/blob/af3a0a1248adc690354de07e5e36e8bcc7314e72/Package.swift#L8) line is overriding Xcode settings forcing `IPHONEOS_DEPLOYMENT_TARGET` to an unsupported SDK version by Xcode 12.

The solution on the thread was remove the `platforms` section, because they support all platforms/versions so this might not work in this case.

**Comment by bogren** [comment]
There is more info on in Cocoapods issue section https://github.com/CocoaPods/CocoaPods/issues/9884. I can create a PR bumping the deployment target as well 👍

**Comment by kristiyandobrev** [comment]
@bogren That would be really nice!  I guess the same could be done for `SPM` as I am getting similar warning

![Screenshot 2020-09-30 at 10 27 33](https://user-images.githubusercontent.com/8437817/94661589-8f5fb280-0307-11eb-96f0-5c8707120d84.png)

**Comment by bogren** [comment]
Yes 👍  Bumped in #325. Need to release.

**Comment by kristiyandobrev** [comment]
@bogren the iOS version in [Package.swift](https://github.com/Skyscanner/SkyFloatingLabelTextField/blob/master/Package.swift#L7l) is still set to `8.0` though 🤔

**Comment by k0nserv** [comment]
I'll try to get a new version out with these fixes today

**Comment by ostoich** [comment]
@k0nserv will you be updating the [Package.swift](https://github.com/Skyscanner/SkyFloatingLabelTextField/blob/master/Package.swift#L7l) file any time soon? It is still set to 8.0 and is causing issues with SPM on XCode 12.

**Comment by devgeek27** [comment]
Same for me. Could you please fix that for SPM.

**Comment by ostoich** [comment]
@k0nserv Xcode 12 is now official. Please update the platforms in [Package.swift](https://github.com/Skyscanner/SkyFloatingLabelTextField/blob/master/Package.swift#L7l) as you promised. 
There are a number of people here waiting on you since [October 2](https://github.com/Skyscanner/SkyFloatingLabelTextField/issues/324#issuecomment-702602629) for this fix.

**Comment by k0nserv** [comment]
Thanks for the reminder, 4.0.0 is out now with the bump

**Comment by diogot** [comment]
Thanks!
