### ISSUE TITLE
placeHolder font is not visible on storyboard like the other inspectable and doesn't impact UI

### ISSUE THREAD

**Issue by pichirichi** [Skyscanner/SkyFloatingLabelTextField#41]
This issue has two items that are relevant for the same property: the placeholder UIFont.
1. I've noticed that **SkyFloatingLabelTextField.swift** has an a definition of

```
    @IBInspectable public var placeholderFont:UIFont? {
        didSet {
            self.updatePlaceholder()
        }
    }
```

However this doesn't reflect on the storyboard inspectable parameters.
2. When setting the **placeholderFont** font in code the change doesn't reflect in the UI.
`self.titleField.placeholderFont             = UIFont(name: kFontRegular, size: 14)`

For the second issue I've followed the debugger and it seems that the new font style is passed but for some reason it doesn't reflect on the UI. 

I'm looking into this but so far no luck, am I missing something?

**Comment by pichirichi** [comment]
I found the problem for issue 2, this was happening since the placeholderFont initialisation was done in the view did load, when it was moved to viewWillLayoutSubviews problem was resolved.
Still no lead on issue 1 (why it is not visible in the storyboard).

**Comment by Deub27** [comment]
You can add the IBInspectable attribute to any property in a class declaration, class extension, or category of type: boolean, integer or floating point number, string, localized string, rectangle, point, size, color, range, and nil.

UIFont seems to be not eligible to @IBInspectable
