### ISSUE TITLE
Can't set text programatically

### ISSUE THREAD

**Issue by pleasantlight** [Skyscanner/SkyFloatingLabelTextField#43]
It looks like the override of the 'text' member breaks the functionality - I'm calling textField.text = "Something" and nothing happens..

Either that or I'm missing something huge here :-/

**Comment by gergelyorosz** [comment]
Hi! In `ShowcaseExampleViewController.swift` at line `82` if I add this line:

```
self.emailField.text = "Hello World"
```

Then I see the text being set as expected:

<img width="367" alt="screen shot 2016-05-16 at 22 14 10" src="https://cloud.githubusercontent.com/assets/1094502/15304133/8ceaffcc-1bb3-11e6-8591-f1291ebec841.png">

Can you share an example on where you can't get the `text` property to work? Without being able to reproduce it, I won't be able to help unfortunately.

**Comment by pleasantlight** [comment]
Hi Gergely,

Sorry man, my bad! I'm doing something weird with a UICollectionView in which the text fields are located, this caused the problem.

Please close and ignore!
