### ISSUE TITLE
how do i validate 4 SkyFloatingLabelTextField?

### ISSUE THREAD

**Issue by arashdoescode** [Skyscanner/SkyFloatingLabelTextField#49]
Let say I have 4 SkyFloatingLabelTextField, how would I validate it in 

one function

```
    func textFieldDidEndEditing(textField: UITextField) {

    }
```

My current Attempt

```
func textFieldDidEndEditing(textField: UITextField) {

        if ((firstnameTextField.text) == "") {
            firstnameTextField.errorMessage = "You must enter your firstname"
        } else {
            firstnameTextField.errorMessage = ""
        }

        if ((lastNameTextField.text) == "") {
            lastNameTextField.errorMessage = "You must enter your lastname"
        } else {
            lastNameTextField.errorMessage = ""
        }


            if (!emailTextField.text!.containsString("@")) {
                emailTextField.errorMessage = "Invalid Email"
            } else {
                emailTextField.errorMessage = ""
            }



        if (passwordTextField.text?.characters.count <= 3) {
            passwordTextField.errorMessage = "Has to be more than 3 characters"
        } else {
            passwordTextField.errorMessage = ""
        }


    }

```

but apparently it shows all the errors at the same time, when I select on one of the text field

**Comment by pichirichi** [comment]
Add a tag to each textField and validate according to the tag. the nested validation above will be hard to maintain.

**Comment by gergelyorosz** [comment]
Hi @arashdoescode . Your code is validating *all* of the textfields, whenever *any one* of these are changed. If you only want to validate the textfield that is being changed, you can follow the [ShowcaseExampleViewController.swift](https://github.com/Skyscanner/SkyFloatingLabelTextField/blob/master/SkyFloatingLabelTextField/SkyFloatingLabelTextFieldExample/Example0/ShowcaseExampleViewController.swift) example and check the instance of `textField` that is being passed in `textFieldDidEndEditing()`.

So in your code:

```
func textFieldDidEndEditing(textField: UITextField) {

        if (textField == firstnameTextField) {
                // firstnameTextField has been changed. Validate this field
                if (firstnameTextField.text) == "") {
                            firstnameTextField.errorMessage = "You must enter your firstname"
                } else {
                      firstnameTextField.errorMessage = ""
                } 
        }
        else if (textField == lastNameTextField) {
           /* And so on... */
        }
    }
```

If you want to validate on every single type, then use `func textField(textField: UITextField, shouldChangeCharactersInRange range: NSRange, replacementString string: String)`.

Also, validating `SkyFloatingLabelTextField` can be done exactly the same way as [validating UITextFields](https://www.google.co.uk/?ion=1&espv=2#q=uitextfield%20validate). We deliberately had `SkyFloatingLabelTextField` inherit from `UITextField` to make common tasks like this easier. If you google around, hopefully you'll find solutions that will also work.

Please let me know if this helps.

**Comment by acecilia** [comment]
As a suggestion, why don't you try validating it applying reactive programming? Right now I am using [RxSwift](https://github.com/ReactiveX/RxSwift) for validating my textFields. There are lots of examples, for example [this](http://stackoverflow.com/questions/34060976/rxswift-enable-disable-button-based-on-textfields-are-not-empty)

**Comment by arashdoescode** [comment]
Thank you gergelyorosz  for helping me

**Comment by hlung** [comment]
You can use `self.emailOrUsernameTextField.addTarget(self, action: #selector(textFieldDidChange), for: .editingChanged)` and `func textFieldDidChange(textField: UITextField) { ... }` to trigger validation on every character change.
