### ISSUE TITLE
can this pod be use without writhing codes

### ISSUE THREAD

**Issue by pprevalon** [Skyscanner/SkyFloatingLabelTextField#52]
can this pod be use without writhing codes. Can i use the textfield from xcode?

**Comment by danipralea** [comment]
Yes you can. You have a plethora of options
![screenshot 2016-10-22 11 05 28](https://cloud.githubusercontent.com/assets/768893/19617975/7bdc5274-9847-11e6-8f4c-b31699ff375e.png)
