### ISSUE TITLE
Swift 2.2 warning

### ISSUE THREAD

**Issue by sprint84** [Skyscanner/SkyFloatingLabelTextField#54]
When compiling in carthage, I am getting this warning message:

SkyFloatingLabelTextField/Sources/SkyFloatingLabelTextField.swift:271:38: warning: use '#selector' instead of explicitly constructing a 'Selector'

**Comment by k0nserv** [comment]
This is a 2.3/2.2 issue I believe? It will be fixed in the next version since #69 has been merged now.
