### ISSUE TITLE
Failed to Update Auto Layout Status

### ISSUE THREAD

**Issue by davidrobertovenegas** [Skyscanner/SkyFloatingLabelTextField#59]
I'm getting the following error:
<img width="348" alt="screen shot 2016-08-01 at 11 19 09 am" src="https://cloud.githubusercontent.com/assets/3959779/17289416/eadc8c92-57d9-11e6-8e25-48fd9e345328.png">

I'm using XCode 8 and swift 2.3.

What do you advice?

**Comment by tentenlee100** [comment]
update cocoapods to 1.0.1 , it will work.

**Comment by MOMMH2008** [comment]
same Problem with me

**Comment by ndrewh** [comment]
This appears to be an issue with Swift 2.3 and Xcode 8. If you let Xcode convert the code to Swift 3 it will work. The converter actually does a pretty good job for the files in this Pod.

**Comment by MaximeChaillou** [comment]
You can add the path /Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/swift/iphonesimulator to the LD_RUNPATH_SEARCH_PATHS setting on the target of SkyFloatingLabelTextField if you use Cocoapods. It worked for me. No error anymore.
Source : https://forums.developer.apple.com/thread/63237

**Comment by skerkewitz** [comment]
Did the **LD_RUNPATH_SEARCH_PATHS** settings fix the problem for somebody else? Because for me it is not working.

**Comment by KiGi** [comment]
Just wanted to say that worked for me also, but I'm really adding this note so that Google can see the error relates to the symbol TMps13OptionSetType - googling for that finds nothing at all!

**Comment by skerkewitz** [comment]
By the way: you can add the fix into your Podfile as post install hook. So you don't have to do it every time you do a `pod update` or `pod install`:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "SkyFloatingLabelTextField"
config.build_settings['LD_RUNPATH_SEARCH_PATHS'].push('/Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/swift/iphonesimulator')
      end
    end
  end
end
```
