### ISSUE TITLE
placeholder text alignment 

### ISSUE THREAD

**Issue by mosn** [Skyscanner/SkyFloatingLabelTextField#68]
Thank you for awesome library. 

Is there anyway to center align placeholder ? 
I can see `textAlignment` only works on `text not placeholder

**Comment by dineshrajas** [comment]
+1

**Comment by k0nserv** [comment]
I don't believe so currently. My assumption is that the label container is only as big as it needs to be to fit the label and thus alignments have no effect. I've not looked at the code though so just speculating now

**Comment by k0nserv** [comment]
You are talking about the label right? I can center the placeholder and text with 

```swift
field.textAlignment = .center
```

*Without value*
![image](https://cloud.githubusercontent.com/assets/1333960/22601918/08175304-ea39-11e6-9963-ef33045206a2.png)

*With value*
![image](https://cloud.githubusercontent.com/assets/1333960/22601926/0f1a1092-ea39-11e6-8b98-b2471262b6fc.png)
_Here the label is not aligned with the rest of the content which is the problem_

**Comment by k0nserv** [comment]
Is this what you are looking for?

```swift
field.textAlignment = .center
field.titleLabel.textAlignment = .center
```

![image](https://cloud.githubusercontent.com/assets/1333960/22602132/de498e1a-ea39-11e6-8cdd-95265a7fe173.png)

**Comment by mosn** [comment]
Yup, That's exactly what I was looking for. 

Thanks

**Comment by k0nserv** [comment]
Great, happy it helped :)
