### ISSUE TITLE
Does the library allow for overriding text that's uppercase

### ISSUE THREAD

**Issue by Downstairz** [Skyscanner/SkyFloatingLabelTextField#70]
The title label is uppercase by default.  Trying to find a way to override it.  I can't find a way to do so.

**Comment by intonarumori** [comment]
@Downstairz 

Check the `titleFormatter` property. By default it will convert the given string to uppercase, but you can set it to anything you like.

https://github.com/Skyscanner/SkyFloatingLabelTextField/blob/master/Sources/SkyFloatingLabelTextField.swift#L144

**Comment by Downstairz** [comment]
@intonarumori thank you!

**Comment by ManiaChamp** [comment]
Can you please remove upercase by default if somebody needs it he can put it up ?
