### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [Skyscanner/SkyFloatingLabelTextField#72]
where to download swift 3 version of this library?

**Comment by c4ndy4ndy** [comment]
@Rashesh-Bosamiya There is a fork of the repo with an existing Swift 3 branch available. Just look at https://github.com/MLSDev/SkyFloatingLabelTextField.

You can easily integrate it with CocoaPods with this one-liner:

pod 'SkyFloatingLabelTextField', git: "https://github.com/MLSDev/SkyFloatingLabelTextField.git", branch: "swift3"

**Comment by codytwinton** [comment]
+1

**Comment by borut-t** [comment]
+1

**Comment by jcarrharris** [comment]
+1

**Comment by eliasturbay** [comment]
+1

**Comment by jaredegan** [comment]
I've been using the MLSDev fork for a while and it's been working like a charm. Hope you can add Swift 3 support in this repo directly to simplify `Podfile` & `podspec` dependencies.

**Comment by wagnercasey** [comment]
Agree with above - the MLSDev swift 3 fork has been flawless. Should definitely get pulled in to main branch.

**Comment by Tibb** [comment]
Same here - I'm based on the MLSDev fork for almost 2 months. Everything is great. This could definitely be pulled into the main branch

**Comment by k0nserv** [comment]
See #55

Closing this so we have a single issue to track this.
