### ISSUE TITLE
RTL support for floating placeholder?

### ISSUE THREAD

**Issue by ghohh** [Skyscanner/SkyFloatingLabelTextField#80]
i changed the text alignment with isLTRLanguage = false or .textallignment = .right

both work for the the actual place holder but not the floating one, how can i manually change the alignment of the floating text?

**Comment by k0nserv** [comment]
This should be fixed in 3.1.0

**Comment by JkThakurMiracle** [comment]
Hi 
I am facing the same problem. 

Actually what i need is. I need my application in RTL. I have changed the appearance of my application from RTL. 
Now i am using textfield with SkyFloatingLabelTextField,  and set its textAllignment to .right.

But when i use to run my app from Xcode it is showing the floating placeholder at the right.
and if i use to run app from device then it makes the floating placeholder at left position.

Please give me the reason.

Thanks

**Comment by JkThakurMiracle** [comment]
Thanks
I found the solution.
