### ISSUE TITLE
Please Update for SWIFT 3 ?

### ISSUE THREAD

**Issue by fadylateef** [Skyscanner/SkyFloatingLabelTextField#83]
everyone's is updating their libraries, thanks in advance for great library

**Comment by Tibb** [comment]
@fadylateef the `master` branch is on Swift3.

First paragraph on the README: 
> From version 2.0 onwards only compatible with Swift 3

;)

**Comment by bogren** [comment]
☝️  As mentioned, versioned 2.0 is compatible with Swift 3. Link to the docs [Docs/installation](https://github.com/Skyscanner/SkyFloatingLabelTextField#installation)

**Comment by dexcell** [comment]
My podfile already set to version 2.0.0
But the this confirmation window still shown for me (using objective c)

**Convert to Current Swift Syntax?**

**Comment by bogren** [comment]
Is your project updated to use Swift 3? If not, I suggest you convert to the lastest syntax. There shouldn't be any code changes if all your pods are supporting Swift 3.

**Comment by dexcell** [comment]
It's a new xcode project (objective c though), should be using swift 3 by default.

As shown here that some of the **SkyFloatingLabelTextField** code developed with earlier version of swift

![screen shot 2016-12-27 at 5 31 25 pm](https://cloud.githubusercontent.com/assets/41800/21497889/998928b4-cc5a-11e6-86c0-e2a66090298b.png)

Click convert will end up throwing errors.

**Comment by bogren** [comment]
Try `pod update SkyFloatingLabelTextField` to pull the lastest version. If that doesn't work you can try to remove the pods folder e.g `rm -rf Pods/`, update the repo `pod repo update` and then reinstall your pods `pod install`.

**Comment by dexcell** [comment]
I even tried to specify git and download the master branch but no luck,
i think you can try to reproduce it, by creating new xcode project with objective c language.

Here is the screenshot again:
![screen shot 2016-12-27 at 7 30 58 pm](https://cloud.githubusercontent.com/assets/41800/21499770/4f33cdda-cc6b-11e6-99e6-9e0354a7618d.png)

**Comment by bogren** [comment]
I can reproduce the issue 👍

**Comment by bogren** [comment]
I'm not sure why Xcode prompt the migration - probably since the project is not setup with Swift. What I did, I choose to migrate, end up with a few errors but the project build and the errors are gone after the build completes. Instead of pushing the changes in `Pods/SkyFloatingLabelTextField` you can delete the pod and reinstall. Your project is going to end up with Swift 3 support, and you'll get a working copy of SkyFloatingLabelTextField 😃

**Comment by dexcell** [comment]
thanks man 🍺
