### ISSUE TITLE
Is possible to decrease placeholder size after animation?

### ISSUE THREAD

**Issue by pmbfish40** [Skyscanner/SkyFloatingLabelTextField#86]

**Comment by k0nserv** [comment]
The placeholder in the field itself?

**Comment by pmbfish40** [comment]
When placeholder animated on top of the text it remains with same size. Will be better if we can set the size of that as well

**Comment by k0nserv** [comment]
Have you tried setting the `placeHolderFont` property?

**Comment by pmbfish40** [comment]
I tried this but nothing changed there

`emailField.placeholderFont = UIFont(name: "MavenPro-Bold", size: 11)`

**Comment by k0nserv** [comment]
Hmm, I'l have to have a try later then. @bogren any ideas?

**Comment by bogren** [comment]
You can use `textField.placeholderFont` to set the placeholder, place make sure the font is imported and available in your project if it's not a default font. 

Use the font property of the title label if you want to edit the font of the text shown above the field. e.g. `textField.titleLabel.font = UIFont(name: "MavenPro-Bold", size: 11)`. Again, please make sure your custom font is imported and is available.
