### ISSUE TITLE
Secure text field for password

### ISSUE THREAD

**Issue by ImranIB** [Skyscanner/SkyFloatingLabelTextField#87]
![simulator screen shot dec 20 2016 6 57 44 am](https://cloud.githubusercontent.com/assets/10369328/21319141/d5749116-c62d-11e6-8cfc-67ac2d518f6d.png)
Hello! Any help how to implement password field using secure text entry because in UIView no such thing exists. 

Thanks.

**Comment by k0nserv** [comment]
This should work out of the box with just

```swift
textField.secureTextEntry = true
```

or

```Objective-C
textField.secureTextEntry = YES;
```

in Objective-C

**Comment by ImranIB** [comment]
![screen shot 2016-12-20 at 10 40 18 pm](https://cloud.githubusercontent.com/assets/10369328/21342035/90241f08-c6b1-11e6-8824-1f522e9978e5.png)

**Comment by ImranIB** [comment]
Actually i am using SkyFloatingLabelTextFieldWithIcon class to show icons in text field.Any help?

**Comment by k0nserv** [comment]
My bad in Swift 3 it would be 

```swift
passwordTextField.isSecureTextEntry = true
```

**Comment by ImranIB** [comment]
Thanks! It worked fine.
