### ISSUE TITLE
show title when the user tap on it

### ISSUE THREAD

**Issue by StevenArmandLee** [Skyscanner/SkyFloatingLabelTextField#90]
hi,
I'm wondering if it is possible to show the title when the user tap on it rather than type something?

**Comment by bogren** [comment]
Hey, there is a few thing you can do to make the title visible. Best result imo, is if you implement the two delegate methods for `textFieldDidBeginEditing(_ textField: UITextField)` and `textFieldDidEndEditing(_ textField: UITextField)`. You can use this [method](https://github.com/Skyscanner/SkyFloatingLabelTextField/blob/master/Sources/SkyFloatingLabelTextField.swift#L415-L422) to hide or show the title. Here is an [example](https://github.com/Skyscanner/SkyFloatingLabelTextField/blob/master/SkyFloatingLabelTextField/SkyFloatingLabelTextFieldExample/Example0/ShowcaseExampleViewController.swift#L120) to show the title, set the completion to nil make it stay, and hide the title again if needed in `textFieldDidEndEditing(_ textField: UITextField)`

**Comment by harrisrap** [comment]
FYI, the link to that method and examples take me to the wrong place. I think I figured it out anyway. I call setTitleVisible(true) in textFieldDidBeginEditing. But now I have the title twice - one as the placeholder and the small one above it. How do I get it to just show the small one above, and have the placeholder blank?
