### ISSUE TITLE
Linker Problem

### ISSUE THREAD

**Issue by Rufy86** [Skyscanner/SkyFloatingLabelTextField#93]
I've added manually this label text field in my objective-c project and added also the framework. when run the project on physical device o simulator all work perfectly but when I built the project to archive and send the package to Apple, the Xcode's Linker say me that:bitcode bundle could not be generated because '.../SkyFloatingLabelTextField.framework/SkyFloatingLabelTextField' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64'

How can I fix it?

P.s. In the SkyFloatingLabelTextField project the folder ObjectiveCExample is Empty and the project SkyFloatingLabelTextFieldObjectiveCExample use cocoapod to insert the framework.

**Comment by k0nserv** [comment]
How are you integrating the project? Are you using CocoaPods? Can you paste your config here please.

@bogren any ideas?

**Comment by Rufy86** [comment]
I'm not using CocoaPods, because I don't like it. in the readme file you write:"You can download the latest files from our Releases page. After doing so, copy the files in the Sources folder to your project."

I've done this, but when I write @import SkyFloatingLabelTextField; Xcode give me an error and ask the framework. so I have to import also the framework but when archive for AppStore, Xcode give me the error written above.

I've done some search in the internet and I've found that I have to archive the framework and import to the project. I've done this and work. now I've send to itunesconnect but all this is not written in readme file. and it's not so intuitive.

**Comment by intonarumori** [comment]
@Rufy86  If you add the source files to the project you shouldn't need any `@import`s.
I will be compiled just as all of your other classes.
Please open a new project, add the source files to that project and try to use it without imports. It should compile and work without any issues. But if it doesn't please send me that clean project so we can take a look.

**Comment by Rufy86** [comment]
@k0nserv I've tried and give me some error.
[prova.zip](https://github.com/Skyscanner/SkyFloatingLabelTextField/files/696497/prova.zip)

i've had to make some edit to build setting. but nothing. don't work.

maybe I don't make something. I don't know

**Comment by intonarumori** [comment]
@Rufy86 
Here's the fixed version:
[prova.zip](https://github.com/Skyscanner/SkyFloatingLabelTextField/files/696685/prova.zip)

I had to change two things:
- when you use Swift code from Obj-C you have to import the automatically generated header file which in your case is `prova-Swift.h`. Not to be confused with the bridging header which is used when you want to use Obj-C code from Swift

- in the build settings I had to change `Use Legacy Swift Language Version` from `yes` to `no` since SkyFloatingLabelTextField is a Swift 3.0 project.

**Comment by k0nserv** [comment]
@Rufy86 can you confirm that the fix from @intonarumori works?

**Comment by Rufy86** [comment]
@k0nserv yes. confirm that the fix from @intonarumori works. I'm sorry for late. but, please! Write correctly how to install manually this framework.

**Comment by k0nserv** [comment]
We encourage the use of a package manager such as CocoaPods or Carthage. This is reason that the instructions for manual integration are sparse, we expect people performing the manual integration to have sufficient expertise in integrating third party project to sort it out themselves. We'll consider it, but I'd recommend you use a package manager instead.

**Comment by Rufy86** [comment]
I understand, but not all people use or want use CocoaPods or Carthage. In fact I hate this package manager. I prefer or make all code or install it manually. If you insert this information, you make your project more complete about the information.

But it only a suggest.

**Comment by intonarumori** [comment]
@Rufy86 If you feel that guide is missing nothing stops you from writing it and contributing yourself.

After I fixed your example and gave you advice about Swift/Obj-C interoperability I believe you have all the information needed.

Please be proactive and contribute, this is an open-source project.
