### ISSUE TITLE
GCC_INSTRUMENT_PROGRAM_FLOW_ARCS in project file

### ISSUE THREAD

**Issue by vytautasgimbutas** [Skyscanner/SkyFloatingLabelTextField#95]
Hi,
i've tried submitting an app which recently has added SkyFloatingLabelTextField and I get an error:
http://stackoverflow.com/questions/34581925/xcode-do-not-submit-apps-with-gcc-style-coverage-ios-upload-processing-error

I see that you set  GCC_INSTRUMENT_PROGRAM_FLOW_ARCS to YES in your project file which seems to me to be what's causing the issue.

**Comment by k0nserv** [comment]
How are you integrating the project?

**Comment by vytautasgimbutas** [comment]
I'm integrating it via Carthage.
I can confirm that after changing the values to NO in release for constants GCC_GENERATE_TEST_COVERAGE_FILES, GCC_INSTRUMENT_PROGRAM_FLOW_ARCS, rebuilding the framework (without checking it out) I was able to upload successfully the binary to iTunes connect. I found that some people also got around this issue with setting bitcode to NO, but in my project it is set to YES and maybe that's why no one else encountered the problem yet.

I found this in Realm changelog, although not mentioned why, but I assume for the very same reason:
```
0.93.2 Release notes (2015-06-12)
=============================================================

### Bugfixes

* Fixed an issue where the packaged OS X Realm.framework was built with
  `GCC_GENERATE_TEST_COVERAGE_FILES` and `GCC_INSTRUMENT_PROGRAM_FLOW_ARCS`
  enabled.

**Comment by k0nserv** [comment]
Thanks, I'll change that an issue a new release.

**Comment by k0nserv** [comment]
This just went out in release 2.0.1. Thanks for reporting and helping find the fix @vytautasgimbutas
