### ISSUE TITLE
Icon showing up as question mark

### ISSUE THREAD

**Issue by Hsanka6** [Skyscanner/SkyFloatingLabelTextField#96]
I added the fontawesome pod but its still not showing when i use 
foodTextField.iconFont = UIFont(name: "FontAwesome", size: 15)
foodTextField.iconText = "\u{f072}"

I'm using swift3

**Comment by k0nserv** [comment]
I suspect this is due to the font not being found. I'm unfamiliar with it myself, can you create a small project that reproduces this?

@bogren any ideas?

**Comment by bogren** [comment]
Make sure the font is added to the plist or if you're using one of the pods that the file using the font imports the pod. As Hugo mentioned, if you upload a small project that reproduces the issue we can take a look 😊

![screen shot 2017-01-17 at 09 31 28](https://cloud.githubusercontent.com/assets/2457281/22013165/f4460f68-dc97-11e6-867e-35627cab26f6.png)

**Comment by Hsanka6** [comment]
@bogren  I have tried that as well as adding the pod

**Comment by Hsanka6** [comment]
Ill post a repo with an example soon

**Comment by Hsanka6** [comment]
does the pod import the ttf file?

**Comment by Hsanka6** [comment]
https://github.com/Hsanka6/samp

**Comment by Hsanka6** [comment]
i added the plist thing and pod still didnt work

**Comment by bogren** [comment]
The pod you're using is not the same thing as we use in SkyFloatingLabelTextField. I have a few options for you: you can add the font.ttf and add it to your project, try this [pod](https://github.com/thii/FontAwesome.swift). With the pod I linked, you can use something like this: (I did a quick test in your sample ✅)
```
someTF.iconFont = UIFont.fontAwesome(ofSize: 15)
someTF.iconText = String.fontAwesomeIcon(name: .plane)
```
 If you really want to use the pod you used in your sample project I suggest you read the readme again, the pod can't be used the same way as it's in SkyFloatingLabelTextField. 
Please note I did not test the following code: 
```
label.setFAIcon(icon: FAType.FAGithub, iconSize: 12)
label.setFAIcon(icon: FAType.FATwitter, iconSize: 12)
```

**Comment by Hsanka6** [comment]
is this the pod you used ? @bogren  pod 'FontAwesome.swift' and did you have the pod and ttf file?

**Comment by bogren** [comment]
Yes, run pod install, and import the pod in the class where you want to use it `import Font_Awesome`, and you should be able to use the code form the snippet I posted ☝️

**Comment by Hsanka6** [comment]
I did what you asked imported font_awesome but my project cant find it and i added the font provided in info.plist. I updated my project on github. Can you check why it's still not working

**Comment by ImranIB** [comment]
First download that font from the link. https://github.com/FortAwesome/Font-Awesome/blob/master/fonts/fontawesome-webfont.ttf. Include it in your project. Add font in info.plist. In xcode use it like that 

emailTextField.iconText = "\u{f003}"

**Comment by Reedyuk** [comment]
To anyone who might get the same issue as i did, with fontawesome swift, some of the selectable fonts are only in certain styles.
If you get the question mark, then try the styles, .solid, .regular, .brands
One of those should then appear.
